[project]
name = "azure-hosted-minecraft"
version = "0.1.0"
description = "A tool for deploying and managing Minecraft servers on Microsoft Azure."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
