[minecraft_server]
[minecraft_server.paper]
# Minecraft Java server version / Paper line
version = "1.21.10"

[minecraft_server.geyser]
# Track latest stable Geyser build compatible with this Paper version
version = "release"

[minecraft_server.floodgate]
# Track latest stable Floodgate build
version = "release"

[minecraft_server.ports]
java = 25565
bedrock = 19132
